import i18n from './util/i18n';

const t = i18n.t.bind(i18n);

export const ALLOW_PDF_LOGIC = false;
export const ALLOW_CALENDAR_VIEW = false;
export const ALLOW_STUDENTS_LOGIC = false;
export const BACKEND_URL = import.meta.env.VITE_BACKEND_URL;

// regex
export const regexFromTo = /^[1-9][0-9]*$/;
export const regexNumberOfQuestions = /^([0-9]|1[0-9]|2[0-9]|3[0])$/;

export const DISALLOWED_INPUT_SYMBOLS = ['e', '-', '+', '.', ','];

export const SUBSCRIPTION_IDS = {
  BASIC: '65e1ee2768139398fb413e1a',
  PRO: '65e1ef2a68139398fb413e1c',
  PRO_QUARTERLY: '65e1efb268139398fb413e24',
};

export const DIFFICULTY = [
  { key: 'easy', i18nKey: 'easy' },
  { key: 'medium', i18nKey: 'medium' },
  { key: 'difficult', i18nKey: 'difficult' },
  { key: 'auto', i18nKey: 'auto' },
];

export const LANGUAGES = [
  { key: 'Auto', name: 'Auto' },
  { key: 'English', name: 'English' },
  { key: 'German', name: 'Deutsch' },
  { key: 'Українська', name: t('Українська') },
  { key: 'Abkhaz', name: 'аҧсуа' },
  { key: 'Afar', name: 'Afaraf' },
  { key: 'Afrikaans', name: 'Afrikaans' },
  { key: 'Akan', name: 'Akan' },
  { key: 'Albanian', name: 'Shqip' },
  { key: 'Amharic', name: 'አማርኛ' },
  { key: 'Arabic', name: 'العربية' },
  { key: 'Aragonese', name: 'Aragonés' },
  { key: 'Armenian', name: 'Հայերեն' },
  { key: 'Assamese', name: 'অসমীয়া' },
  { key: 'Avaric', name: 'авар мацӀ, магӀарул мацӀ' },
  { key: 'Avestan', name: 'avesta' },
  { key: 'Aymara', name: 'aymar aru' },
  { key: 'Azerbaijani', name: 'azərbaycan dili' },
  { key: 'Bambara', name: 'bamanankan' },
  { key: 'Bashkir', name: 'башҡорт теле' },
  { key: 'Basque', name: 'euskara, euskera' },
  { key: 'Belarusian', name: 'Беларуская' },
  { key: 'Bengali', name: 'বাংলা' },
  { key: 'Bihari', name: 'भोजपुरी' },
  { key: 'Bislama', name: 'Bislama' },
  { key: 'Bosnian', name: 'bosanski jezik' },
  { key: 'Breton', name: 'brezhoneg' },
  { key: 'Bulgarian', name: 'български език' },
  { key: 'Burmese', name: 'ဗမာစာ' },
  { key: 'Catalan', name: 'Català' },
  { key: 'Chamorro', name: 'Chamoru' },
  { key: 'Chechen', name: 'нохчийн мотт' },
  { key: 'Chichewa', name: 'chiCheŵa, chinyanja' },
  { key: 'Chinese', name: '中文 (Zhōngwén), 汉语, 漢語' },
  { key: 'Chuvash', name: 'чӑваш чӗлхи' },
  { key: 'Cornish', name: 'Kernewek' },
  { key: 'Corsican', name: 'corsu, lingua corsa' },
  { key: 'Cree', name: 'ᓀᐦᐃᔭᐍᐏᐣ' },
  { key: 'Croatian', name: 'hrvatski' },
  { key: 'Czech', name: 'česky, čeština' },
  { key: 'Danish', name: 'dansk' },
  { key: 'Divehi', name: 'ދިވެހި' },
  { key: 'Dutch', name: 'Nederlands, Vlaams' },
  { key: 'Esperanto', name: 'Esperanto' },
  { key: 'Estonian', name: 'eesti, eesti keel' },
  { key: 'Ewe', name: 'Eʋegbe' },
  { key: 'Faroese', name: 'føroyskt' },
  { key: 'Fijian', name: 'vosa Vakaviti' },
  { key: 'Finnish', name: 'suomi, suomen kieli' },
  { key: 'French', name: 'français, langue française' },
  { key: 'Fula', name: 'Fulfulde, Pulaar, Pular' },
  { key: 'Galician', name: 'Galego' },
  { key: 'Georgian', name: 'ქართული' },
  { key: 'Greek, Modern', name: 'Ελληνικά' },
  { key: 'Guaraní', name: 'Avañeẽ' },
  { key: 'Gujarati', name: 'ગુજરાતી' },
  { key: 'Haitian', name: 'Kreyòl ayisyen' },
  { key: 'Hausa', name: 'Hausa, هَوُسَ' },
  { key: 'Hebrew (modern)', name: 'עברית' },
  { key: 'Herero', name: 'Otjiherero' },
  { key: 'Hindi', name: 'हिन्दी, हिंदी' },
  { key: 'Hiri Motu', name: 'Hiri Motu' },
  { key: 'Hungarian', name: 'Magyar' },
  { key: 'Interlingua', name: 'Interlingua' },
  { key: 'Indonesian', name: 'Bahasa Indonesia' },
  { key: 'Interlingue', name: 'Originally called Occidental; then Interlingue after WWII' },
  { key: 'Irish', name: 'Gaeilge' },
  { key: 'Igbo', name: 'Asụsụ Igbo' },
  { key: 'Inupiaq', name: 'Iñupiaq, Iñupiatun' },
  { key: 'Ido', name: 'Ido' },
  { key: 'Icelandic', name: 'Íslenska' },
  { key: 'Italian', name: 'Italiano' },
  { key: 'Inuktitut', name: 'ᐃᓄᒃᑎᑐᑦ' },
  { key: 'Japanese', name: '日本語 (にほんご／にっぽんご)' },
  { key: 'Javanese', name: 'basa Jawa' },
  { key: 'Kalaallisut', name: 'kalaallisut, kalaallit oqaasii' },
  { key: 'Kannada', name: 'ಕನ್ನಡ' },
  { key: 'Kanuri', name: 'Kanuri' },
  { key: 'Kashmiri', name: 'कश्मीरी, كشميري‎' },
  { key: 'Kazakh', name: 'Қазақ тілі' },
  { key: 'Khmer', name: 'ភាសាខ្មែរ' },
  { key: 'Kikuyu', name: 'Gĩkũyũ' },
  { key: 'Kinyarwanda', name: 'Ikinyarwanda' },
  { key: 'Kirghiz', name: 'кыргыз тили' },
  { key: 'Komi', name: 'коми кыв' },
  { key: 'Kongo', name: 'KiKongo' },
  { key: 'Korean', name: '한국어 (韓國語), 조선말 (朝鮮語)' },
  { key: 'Kurdish', name: 'Kurdî, كوردی‎' },
  { key: 'Kwanyama', name: 'Kuanyama' },
  { key: 'Latin', name: 'latine, lingua latina' },
  { key: 'Luxembourgish', name: 'Lëtzebuergesch' },
  { key: 'Luganda', name: 'Luganda' },
  { key: 'Limburgish', name: 'Limburgs' },
  { key: 'Lingala', name: 'Lingála' },
  { key: 'Lao', name: 'ພາສາລາວ' },
  { key: 'Lithuanian', name: 'lietuvių kalba' },
  { key: 'Luba-Katanga', name: 'luba katanga' },
  { key: 'Latvian', name: 'latviešu valoda' },
  { key: 'Manx', name: 'Gaelg, Gailck' },
  { key: 'Macedonian', name: 'македонски јазик' },
  { key: 'Malagasy', name: 'Malagasy fiteny' },
  { key: 'Malay', name: 'bahasa Melayu, بهاس ملايو‎' },
  { key: 'Malayalam', name: 'മലയാളം' },
  { key: 'Maltese', name: 'Malti' },
  { key: 'Māori', name: 'te reo Māori' },
  { key: 'Marathi', name: 'मराठी' },
  { key: 'Marshallese', name: 'Kajin M̧ajeļ' },
  { key: 'Mongolian', name: 'монгол' },
  { key: 'Nauru', name: 'Ekakairũ Naoero' },
  { key: 'Navajo', name: 'Diné bizaad, Dinékʼehǰí' },
  { key: 'Norwegian Bokmål', name: 'Norsk bokmål' },
  { key: 'North Ndebele', name: 'isiNdebele' },
  { key: 'Nepali', name: 'नेपाली' },
  { key: 'Ndonga', name: 'Owambo' },
  { key: 'Norwegian Nynorsk', name: 'Norsk nynorsk' },
  { key: 'Norwegian', name: 'Norsk' },
  { key: 'Nuosu', name: 'ꆈꌠ꒿ Nuosuhxop' },
  { key: 'South Ndebele', name: 'isiNdebele' },
  { key: 'Occitan', name: 'Occitan' },
  { key: 'Ojibwe', name: 'ᐊᓂᔑᓈᐯᒧᐎᓐ' },
  { key: 'Old Church Slavonic', name: 'ѩзыкъ словѣньскъ' },
  { key: 'Oromo', name: 'Afaan Oromoo' },
  { key: 'Oriya', name: 'ଓଡ଼ିଆ' },
  { key: 'Ossetian', name: 'ирон æвзаг' },
  { key: 'Panjabi', name: 'ਪੰਜਾਬੀ, پنجابی‎' },
  { key: 'Pāli', name: 'पाऴि' },
  { key: 'Persian', name: 'فارسی' },
  { key: 'Polish', name: 'polski' },
  { key: 'Pashto', name: 'پښتو' },
  { key: 'Portuguese', name: 'Português' },
  { key: 'Quechua', name: 'Runa Simi, Kichwa' },
  { key: 'Romansh', name: 'rumantsch grischun' },
  { key: 'Kirundi', name: 'Ikirundi' },
  { key: 'Russian', name: 'русский язык' },
  { key: 'Sanskrit', name: 'संस्कृतम्' },
  { key: 'Sardinian', name: 'sardu' },
  { key: 'Sindhi', name: 'सिन्धी, سنڌي، سندھی‎' },
  { key: 'Northern Sami', name: 'Davvisámegiella' },
  { key: 'Samoan', name: 'gagana faa Samoa' },
  { key: 'Sango', name: 'yângâ tî sängö' },
  { key: 'Serbian', name: 'српски језик' },
  { key: 'Scottish Gaelic', name: 'Gàidhlig' },
  { key: 'Shona', name: 'chiShona' },
  { key: 'Sinhala', name: 'සිංහල' },
  { key: 'Slovak', name: 'slovenčina' },
  { key: 'Slovene', name: 'slovenščina' },
  { key: 'Somali', name: 'Soomaaliga, af Soomaali' },
  { key: 'Southern Sotho', name: 'Sesotho' },
  { key: 'Spanish', name: 'Español' },
  { key: 'Sundanese', name: 'Basa Sunda' },
  { key: 'Swahili', name: 'Kiswahili' },
  { key: 'Swati', name: 'SiSwati' },
  { key: 'Swedish', name: 'svenska' },
  { key: 'Tamil', name: 'தமிழ்' },
  { key: 'Telugu', name: 'తెలుగు' },
  { key: 'Tajik', name: 'тоҷикӣ, toçikī, تاجیکی‎' },
  { key: 'Thai', name: 'ไทย' },
  { key: 'Tigrinya', name: 'ትግርኛ' },
  { key: 'Tibetan Standard', name: 'བོད་ཡིག' },
  { key: 'Turkmen', name: 'Türkmen, Түркмен' },
  { key: 'Tagalog', name: 'Wikang Tagalog' },
  { key: 'Tswana', name: 'Setswana' },
  { key: 'Tonga', name: 'faka Tonga' },
  { key: 'Turkish', name: 'Türkçe' },
  { key: 'Tsonga', name: 'Xitsonga' },
  { key: 'Tatar', name: 'татар теле, tatar tele' },
  { key: 'Twi', name: 'Twi' },
  { key: 'Tahitian', name: 'Reo Tahiti' },
  { key: 'Uighur', name: 'ئۇيغۇرچە‎, Uyghurche' },
  { key: 'Urdu', name: 'اردو' },
  { key: 'Uzbek', name: 'zbek, Ўзбек, أۇزبېك‎' },
  { key: 'Venda', name: 'Tshivenḓa' },
  { key: 'Vietnamese', name: 'Tiếng Việt' },
  { key: 'Volapük', name: 'Volapük' },
  { key: 'Walloon', name: 'Walon' },
  { key: 'Welsh', name: 'Cymraeg' },
  { key: 'Wolof', name: 'Wollof' },
  { key: 'Western Frisian', name: 'Frysk' },
  { key: 'Xhosa', name: 'isiXhosa' },
  { key: 'Yiddish', name: 'ייִדיש' },
  { key: 'Yoruba', name: 'Yorùbá' },
  { key: 'Zhuang', name: 'Saɯ cueŋƅ, Saw cuengh' },
  { key: 'Zulu', name: 'isiZulu' },
];
